services:

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    environment:
      - API_URL=https://castles.dobschal.eu/api
    ports:
      - "4001:80"
    networks:
      - castles

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "4000:3000"
    networks:
      - castles
    environment:
      - JWT_PUBLIC_KEY_PATH=/jwt/publicKey.pem
      - JWT_PPRIVATE_KEY_PATH=/jwt/privateKey.pem
    volumes:
      - type: bind
        source: ./jwt
        target: /jwt

  database:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=castles
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - castles

volumes:
  db:
    driver: local

networks:
  castles:
    external: true
