services:

  client:
    image: dobschal/castles-2025:client-latest
    restart: always
    environment:
      - API_URL=https://castles.games/api
    ports:
      - "4001:80"
    networks:
      - castles

  server:
    image: dobschal/castles-2025:server-latest
    restart: always
    ports:
      - "4000:3000"
    depends_on:
      - database
    networks:
      - castles
    environment:
      - JWT_PUBLIC_KEY_PATH=/jwt/publicKey.pem
      - JWT_PRIVATE_KEY_PATH=/jwt/privateKey.pem
    volumes:
      - type: bind
        source: ./jwt
        target: /jwt

  database:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=castles
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - castles

volumes:
  db:
    driver: local

networks:
  castles:
    external: true
