export enum EventType {
  BUILDING_CREATED = "BUILDING_CREATED",
  UNIT_CREATED = "UNIT_CREATED",
  UNIT_MOVED = "UNIT_MOVED",
  BEER_COLLECTED = "BEER_COLLECTED",
  LOST_UNIT = "LOST_UNIT",
  BUILDING_CONQUERED = "BUILDING_CONQUERED",
  BUILDING_DESTROYED = "BUILDING_DESTROYED",
}
