export enum TutorialType {
  FIRST_WORKER = "FIRST_WORKER",
  FIRST_FARM = "FIRST_FARM",
  FIRST_BREWERY = "FIRST_BREWERY",
  FIRST_BEER_COLLECTED = "FIRST_BEER_COLLECTED",
  FIRST_CASTLE = "FIRST_CASTLE",
  FIRST_UNIT = "FIRST_UNIT",
}
