name: Docker Build and Push

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build_and_push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Server Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/castles-2025:server-latest ./server

      - name: Push Docker Server Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/castles-2025:server-latest

      - name: Build Docker Client Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/castles-2025:client-latest ./client

      - name: Push Docker Client Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/castles-2025:client-latest

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/hetzner.key
          chmod 600 ~/.ssh/hetzner.key
          cat >>~/.ssh/config <<END
          Host hetzner
            HostName $SSH_HOST
            User root
            IdentityFile ~/.ssh/hetzner.key
            StrictHostKeyChecking no
            ServerAliveInterval 600
          END
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
          SSH_HOST: ${{ secrets.HOST }}

      - name: Fetch latest GitHub repo
        run: ssh hetzner 'cd /root/deployments/castles-2025 && git fetch && git reset --hard origin/main'
      
      - name: Pull image and restart
        run: ssh hetzner 'cd /root/deployments/castles-2025 && docker compose pull  && docker compose up -d'
      
      - name: Delete old docker images
        run: ssh hetzner 'docker system prune -f'
        
